[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.88"
version = "0.1.0"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
unused_lifetimes = "warn"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "warn"
panic = "warn"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
sonic-rs = "0.5.8"
regex = "1.13.1"
jiff = "0.2.35"
memchr = "2.8.3"
smallvec = { version = "1.15.2", features = ["union", "const_generics"] }
compact_str = "0.10.0"
slab = "0.4"
napi = { version = "3.12", default-features = false, features = ["napi9"] }
napi-derive = "3.6"
napi-build = "2.4"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
