/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Compiles a serialized plan and registers it in the slab.
 *
 * # Errors
 *
 * Returns an error when the plan JSON cannot be deserialized or when its
 * arena is structurally invalid.
 */
export declare function compile(planJson: string): number

/** Removes a compiled plan from the slab. Unknown handles are a no-op. */
export declare function dispose(plan: number): void

/**
 * Validates raw JSON bytes against a compiled plan. The hot path.
 *
 * # Errors
 *
 * Returns an error when `plan` is not a registered handle.
 */
export declare function validateJson(plan: number, input: Uint8Array): Verdict

/**
 * The result of a byte-path validation, mirroring the JS-facing contract.
 *
 * `status` is 0 when the input bytes are already canonical, 1 when `payload`
 * holds the canonical output JSON, 2 when `payload` holds the raw issue array
 * JSON, and 3 when the plan is not JSON-eligible or the input could not be
 * parsed — the caller then uses the TypeScript path.
 */
export interface Verdict {
  /**
   * Verdict code: 0 valid-canonical, 1 valid-rewritten, 2 invalid, 3
   * fall back to the JS path.
   */
  status: number
  /** Output or issue JSON, present for statuses 1 and 2 only. */
  payload?: string
}
